### ISSUE TITLE
Huge bundle size

### ISSUE THREAD

**Issue by Rahuletto** [Onemind-Services-LLC/react-icons-ng#15]
### Describe the bug

The `react-icons-ng` is too big and nearly occupy 60-70% of my bundle size
![image](https://github.com/Onemind-Services-LLC/react-icons-ng/assets/71836991/e02d81f0-3cf2-49f5-b98d-5b65339f5ab5)

Most of the site bundle is increased by the icons
![image](https://github.com/Onemind-Services-LLC/react-icons-ng/assets/71836991/2e8d088a-37d6-4580-8567-4d59d82bf266)

### Expected behavior

Should have a way to import just one icon instead of all icons from a folder and bloat the bundle size

### Minimal sample repository URL

https://github.com/Rahuletto/CodeBoard/tree/dev

### Steps To Reproduce

I dont think this needs an reproduction step, run with @next/bundle-analyzer

### Package version

v4.8.5

### Additional context

Wanted a way to import specific icon instead of all files from a icon type.

**Comment by abhi1693** [comment]
Thank you for opening the bug report. Would you like to submit a PR to help resolve the issue?

**Comment by Rahuletto** [comment]
I would love to but this requires sooo much time (that it cannot be worth it) and so many files which can ruin the simplicity and the file hierarchy.

**Comment by abhi1693** [comment]
Due to the limitations of NPM registry to hold huge number of files, I'm going to chage the registry to GitHub NPM registry which does not have this limitation.

We will publish 2 kinds of packages for now

- The standard library which we have been pubslishing on the NPM registry (react-icons-ng).
- The pack library which will have all Icons as separate files (react-icons-ng-pack)

I'm hoping that `react-icons-ng-pack` will later be transformed into `react-icons-ng` if this library is better to reduce the bundle size.

**Comment by abhi1693** [comment]
@Rahuletto Try the new `reack-icons-ng-pack`, it'll help reduce the size of your bundle drastically. I tested this in a vite react project and the bundle reduced from 128KB to 10.43KB

**Comment by Rahuletto** [comment]
> @Rahuletto Try the new `reack-icons-ng-pack`, it'll help reduce the size of your bundle drastically. I tested this in a vite react project and the bundle reduced from 128KB to 10.43KB

Oh thank you very much 💗 I'll definitely try it out

**Comment by masterkain** [comment]
I would test it but I have issues with yarn 3 installing the package, in a next.js project .yarnrc.yml:

```
enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.2.cjs

npmScopes:
  onemind-services-llc:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAlwaysAuth: false
```

but I always get, on install

`➤ YN0041: │ @onemind-services-llc/react-icons-ng-pack@npm:5.0.1: Invalid authentication (as an anonymous user)`

on add:

`➤ YN0027: @onemind-services-llc/react-icons-ng-pack@unknown can't be resolved to a satisfying range`

any tips?

**Comment by masterkain** [comment]
this is still a problem

**Comment by abhi1693** [comment]
Not until they allow huge packages to be uploaded. I only found GitHub that had no limit on the package size.
